<a href="https://colab.research.google.com/github/neip313/Python_Machine_Learning/blob/main/03_ndarray_%EB%8D%B0%EC%9D%B4%ED%84%B0_%EC%83%9D%EC%84%B1%ED%95%98%EA%B8%B0(random_%EC%84%9C%EB%B8%8C_%EB%AA%A8%EB%93%88_%ED%95%A8%EC%88%98_%EC%9D%B4%EC%9A%A9)_After.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### 학습목표
 - random 서브모듈 함수를 통해 ndarray 생성하기

In [2]:
import numpy as np

#### random 서브모듈

#### rand 함수
 - 0, 1사이의 분포로 랜덤한 ndarray 생성

In [3]:
np.random.rand(4, 5, 3)

array([[[0.16639286, 0.87690277, 0.40703534],
        [0.38618927, 0.93367101, 0.577955  ],
        [0.64102744, 0.50417359, 0.72838112],
        [0.60926719, 0.76902408, 0.52431149],
        [0.69822445, 0.30487155, 0.15669416]],

       [[0.57129936, 0.8053363 , 0.69714289],
        [0.26967083, 0.92909215, 0.76482671],
        [0.89990099, 0.5825801 , 0.76018347],
        [0.82362361, 0.92094325, 0.22268407],
        [0.69584503, 0.83941588, 0.8253616 ]],

       [[0.14241744, 0.89491227, 0.27651781],
        [0.87497683, 0.45244773, 0.92097588],
        [0.86556238, 0.07174219, 0.8347333 ],
        [0.70745075, 0.29464525, 0.10396343],
        [0.30479712, 0.00537667, 0.76051148]],

       [[0.35844405, 0.4900895 , 0.24204358],
        [0.64868354, 0.39985269, 0.62862429],
        [0.10344596, 0.25968141, 0.50710251],
        [0.97265486, 0.80299072, 0.64551836],
        [0.21281304, 0.25013583, 0.53634935]]])

#### randn함수
 - n: normal distribution(정규분포)
 - 정규분포로 샘플링된 랜덤 ndarray 생성

In [4]:
np.random.randn(5)

array([-0.68651288, -1.37996345,  1.24497354, -0.06947069,  0.98015995])

In [5]:
np.random.randn(3, 4, 2)

array([[[ 0.69244773,  1.22300763],
        [-0.85306609, -0.04699105],
        [-1.83276872,  1.0471796 ],
        [-0.80014479, -1.90665087]],

       [[ 0.72078552, -0.68321196],
        [ 0.34136029, -0.22652988],
        [ 0.07040334,  0.24079177],
        [-0.83669599,  0.30199401]],

       [[ 0.76129057, -0.88818153],
        [-0.56127873, -0.55095391],
        [ 0.76179461,  0.74445828],
        [-0.14517825, -0.3413311 ]]])

#### randint 함수
 - 특정 정수 사이에서 랜덤하게 샘플링

In [6]:
np.random.randint(1, 100, size=(5,))

array([82, 24, 71, 89, 34])

#### seed 함수
 - 랜덤한 값을 동일하게 다시 생성하고자 할때 사용

In [7]:
np.random.seed(23)
np.random.randn(3, 4)

array([[ 0.66698806,  0.02581308, -0.77761941,  0.94863382],
       [ 0.70167179, -1.05108156, -0.36754812, -1.13745969],
       [-1.32214752,  1.77225828, -0.34745899,  0.67014016]])

#### choice
 - 주어진 1차원 ndarray로 부터 랜덤으로 샘플링
 - 정수가 주어진 경우, np.arange(해당숫자)로 간주

In [8]:
np.random.choice(100, size=(3, 4))

array([[79, 90, 62, 57],
       [19, 33, 59, 39],
       [15, 36, 65,  1]])

In [9]:
x = np.array([1, 2, 3, 1.5, 2.6, 4.9])
np.random.choice(x, size=(2, 2), replace=False)

array([[1. , 2. ],
       [3. , 4.9]])

#### 확률분포에 따른 ndarray 생성
 - uniform
 - normal 등등

In [10]:
np.random.uniform(1.0, 3.0, size=(4, 5))

array([[2.51225457, 2.66736254, 1.34436822, 1.42430685, 2.74942904],
       [1.8654592 , 2.75215591, 1.94121243, 1.60485579, 2.53464481],
       [1.02068753, 2.35248663, 1.94336175, 2.26833065, 2.84085397],
       [1.26336399, 2.67879335, 2.40971945, 2.93578399, 2.80844986]])

In [11]:
np.random.normal(size=(3, 4))
np.random.randn(3, 4)

array([[-1.10028295,  0.19820952,  0.0407598 ,  0.78145406],
       [ 0.06493754, -0.15102838, -0.01601653,  1.5072508 ],
       [-1.60482532,  1.78616035, -0.2363808 , -2.42559596]])